apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
  volumeMode: Filesystem