apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry
  sessionAffinity: None
  type: ClusterIP