apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry-ui
  sessionAffinity: None
  type: ClusterIP